module.exports = {
	channels: {
		project: {
			BACKGROUND_READY: 'BACKGROUND_READY',
			GENERATE_REQUEST: 'GENERATE_PROJECT_REQUEST',
			GENERATE_SUCCESS: 'GENERATE_PROJECT_SUCCESS',
			GENERATE_PROJECT: 'GENERATE_PROJECT',
			EXPORT: 'EXPORT_PROJECT',
		},
	},
};
